import { SafeUrl } from '@angular/platform-browser';

export interface ChatMessage {
  messageId: number;
  clientTempId?: number; // ✅ ADD THIS: The temporary ID generated by the client
  conversationId: number;
  senderUsername: string;
  content: string;
  sentAt: string;
  attachments: Attachment[];
  status?: 'sending' | 'sent' | 'error';
}

export interface Attachment {
  fileUrl: string | SafeUrl;
  fileName: string;
  fileType: string;
  _originalUrl?: string; // Stores the raw blob URL for cleanup
}