import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from '../../../../environments/environment';
import { WebSocketService } from '../../../core/services/websocket.service';
import { ChatMessage } from '../../../shared/models/chat.model';
import { Conversation } from '../../../shared/models/conversation.model'; // ✅ 1. Import Conversation model

@Injectable({
  providedIn: 'root'
})
export class ChatService {
  private readonly http = inject(HttpClient);
  private readonly webSocketService = inject(WebSocketService);
  private readonly apiUrl = environment.apiUrl;

  getMessageHistory(conversationId: number): Observable<ChatMessage[]> {
    return this.http.get<ChatMessage[]>(`${this.apiUrl}/chat/${conversationId}/messages`);
  }

  watchConversation(conversationId: number): Observable<ChatMessage> {
    const topic = `/topic/conversation/${conversationId}`;
    return this.webSocketService.watch<ChatMessage>(topic);
  }

  /**
   * Sends a message.
   * @param conversationId The conversation to send to.
   * @param content The text content of the message.
   * @param files Any files to be attached.
   * @param clientTempId The unique temporary ID generated by the client.
   */
  sendMessage(conversationId: number, content: string, files: File[], clientTempId: number): Observable<any> {
    if (files && files.length > 0) {
      const formData = new FormData();
      // ✅ Include the temporary ID in the DTO
      const messageDto = { content, clientTempId };
      formData.append('message', new Blob([JSON.stringify(messageDto)], { type: 'application/json' }));
      files.forEach(file => {
        formData.append('files', file, file.name);
      });
      return this.http.post(`${this.apiUrl}/chat/${conversationId}/message`, formData);
    } else {
      const destination = `/app/chat/${conversationId}/sendMessage`;
      // ✅ Include the temporary ID in the DTO for text messages too
      const messageDto = { content, clientTempId };
      this.webSocketService.sendMessage(destination, messageDto);
      return new Observable(sub => sub.complete());
    }
  }

  getSingleMessage(messageId: number): Observable<ChatMessage> {
    return this.http.get<ChatMessage>(`${this.apiUrl}/messages/${messageId}`);
  }

  getConversations(): Observable<Conversation[]> {
    return this.http.get<Conversation[]>(`${this.apiUrl}/chat/conversations`);
  }

  findOrCreateConversation(participantId: number): Observable<Conversation> {
    return this.http.post<Conversation>(`${this.apiUrl}/chat/conversations`, { participantId });
  }

  markAsRead(conversationId: number): Observable<void> {
    return this.http.post<void>(`${this.apiUrl}/chat/conversations/${conversationId}/read`, {});
  }
}